In [35]:
import pandas as pd
import numpy as np
import matplotlib as mp

filename = "Data/B2C.csv"
df_B2C = pd.read_csv(filename)

In [36]:
df_B2C

,Data,Artigo,Quantidade,PrecoLiquido,Vendedor
0,2024-11-24 19:43:39.000,OAMB3208LP,-1,-31.71,603.0
1,2024-11-24 19:43:39.000,NaN,0,0.00,NaN
2,2024-11-24 19:43:39.000,NaN,0,0.00,NaN
3,2024-11-24 19:43:39.000,NaN,0,0.00,NaN
4,2024-11-24 17:42:12.000,NaN,0,0.00,NaN
...,...,...,...,...,...
191764,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191765,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191766,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191767,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191768,2023-01-02 10:18:14.000,OSW9371RM22L,-1,-72.44,NaN

In [37]:
df_B2C.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191769 entries, 0 to 191768
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Data          191769 non-null  object
 1   Artigo        157525 non-null  object
 2   Quantidade    191769 non-null  int64
 3   PrecoLiquido  191769 non-null  float64
 4   Vendedor      107257 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 7.3+ MB

In [38]:
df_B2C.shape

(191769, 5)

In [39]:
df_B2C.head(5)

                      Data      Artigo  Quantidade  PrecoLiquido  Vendedor
0  2024-11-24 19:43:39.000  OAMB3208LP          -1        -31.71     603.0
1  2024-11-24 19:43:39.000         NaN           0          0.00       NaN
2  2024-11-24 19:43:39.000         NaN           0          0.00       NaN
3  2024-11-24 19:43:39.000         NaN           0          0.00       NaN
4  2024-11-24 17:42:12.000         NaN           0          0.00       NaN

In [40]:
df_B2C.tail(5)

,Data,Artigo,Quantidade,PrecoLiquido,Vendedor
191764,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191765,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191766,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191767,2023-01-02 10:18:14.000,NaN,0,0.00,NaN
191768,2023-01-02 10:18:14.000,OSW9371RM22L,-1,-72.44,NaN

In [41]:
df_B2C[df_B2C['Artigo'].isna()].describe()

         Quantidade  PrecoLiquido  Vendedor
count  34244.000000  34244.000000       0.0
mean       0.029582      0.144618       NaN
std        0.170977      6.398343       NaN
min       -1.000000    -50.000000       NaN
25%        0.000000      0.000000       NaN
50%        0.000000      0.000000       NaN
75%        0.000000      0.000000       NaN
max        1.000000   1173.920000       NaN

In [42]:
df_B2C[df_B2C['Artigo'].isna()]

                           Data Artigo  Quantidade  PrecoLiquido  Vendedor
1       2024-11-24 19:43:39.000    NaN           0           0.0       NaN
2       2024-11-24 19:43:39.000    NaN           0           0.0       NaN
3       2024-11-24 19:43:39.000    NaN           0           0.0       NaN
4       2024-11-24 17:42:12.000    NaN           0           0.0       NaN
5       2024-11-24 17:42:12.000    NaN           0           0.0       NaN
...                         ...    ...         ...           ...       ...
191762  2023-01-02 10:36:20.000    NaN           0           0.0       NaN
191764  2023-01-02 10:18:14.000    NaN           0           0.0       NaN
191765  2023-01-02 10:18:14.000    NaN           0           0.0       NaN
191766  2023-01-02 10:18:14.000    NaN           0           0.0       NaN
191767  2023-01-02 10:18:14.000    NaN           0           0.0       NaN

[34244 rows x 5 columns]

In [43]:
df_B2C['Artigo_Status'] = df_B2C['Artigo'].apply(
    lambda x: 'Sem Artigo' if pd.isna(x) else 'Com Artigo'
)#cria a coluna que diz se esta null o artigo ou não

In [44]:
df_B2C

,Data,Artigo,Quantidade,PrecoLiquido,Vendedor,Artigo_Status
0,2024-11-24 19:43:39.000,OAMB3208LP,-1,-31.71,603.0,Com Artigo
1,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
2,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
3,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
4,2024-11-24 17:42:12.000,NaN,0,0.00,NaN,Sem Artigo
...,...,...,...,...,...,...
191764,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191765,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191766,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191767,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191768,2023-01-02 10:18:14.000,OSW9371RM22L,-1,-72.44,NaN,Com Artigo

In [45]:
df_B2C

,Data,Artigo,Quantidade,PrecoLiquido,Vendedor,Artigo_Status
0,2024-11-24 19:43:39.000,OAMB3208LP,-1,-31.71,603.0,Com Artigo
1,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
2,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
3,2024-11-24 19:43:39.000,NaN,0,0.00,NaN,Sem Artigo
4,2024-11-24 17:42:12.000,NaN,0,0.00,NaN,Sem Artigo
...,...,...,...,...,...,...
191764,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191765,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191766,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191767,2023-01-02 10:18:14.000,NaN,0,0.00,NaN,Sem Artigo
191768,2023-01-02 10:18:14.000,OSW9371RM22L,-1,-72.44,NaN,Com Artigo

In [48]:
df_B2C.to_csv('B2C_clean.csv', index=False)