In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp

filename = "Data/Sell_Out.csv"
df_SO = pd.read_csv(filename)

/var/folders/qm/bcpltlfs7qj3bt894_htm00c0000gn/T/ipykernel_2426/1730639872.py:6: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_SO = pd.read_csv(filename)

In [2]:
df_SO

,Data,Cod. Vendedor,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
0,01/01/2023,-,-,40002411,OSW9317SS22L,3.0,272
1,01/01/2023,-,-,5021201,OSW9317RM22L,3.0,173
2,01/01/2023,-,-,16001002,OSW9371SM22L,3.0,153
3,01/01/2023,020,-,16001003,OJEBM03A-M,3.0,53
4,01/01/2023,022,-,4001102,OJEBMBSO01,3.0,45
...,...,...,...,...,...,...,...
1048560,20/01/2023,012,-,2000801,OL9267SD22L,1.0,-25
1048561,20/01/2023,012,-,2000801,OL9267SS22L,1.0,-25
1048562,20/01/2023,012,-,2000801,OL9273BB21L,1.0,-25
1048563,20/01/2023,012,-,2000801,OL9273SS21L,1.0,-25
1048564,20/01/2023,012,-,2000801,OL9346SR22L,1.0,-25

In [3]:
df_SO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048565 entries, 0 to 1048564
Data columns (total 7 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Data                  1048565 non-null  object
 1   Cod. Vendedor         1048565 non-null  object
 2   Cod. Cliente Holding  1048565 non-null  object
 3   Cod. Cliente          1048565 non-null  object
 4   Cod. Artigo           1048565 non-null  object
 5   Quantidade            1048565 non-null  float64
 6   Valor Líq. EUR        1048565 non-null  int64
dtypes: float64(1), int64(1), object(5)
memory usage: 56.0+ MB

In [4]:
df_SO.shape

(1048565, 7)

In [5]:
df_SO.head(5)

,Data,Cod. Vendedor,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
0,01/01/2023,-,-,40002411,OSW9317SS22L,3.0,272
1,01/01/2023,-,-,5021201,OSW9317RM22L,3.0,173
2,01/01/2023,-,-,16001002,OSW9371SM22L,3.0,153
3,01/01/2023,020,-,16001003,OJEBM03A-M,3.0,53
4,01/01/2023,022,-,4001102,OJEBMBSO01,3.0,45

In [6]:
df_SO.tail(5)

,Data,Cod. Vendedor,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
1048560,20/01/2023,012,-,2000801,OL9267SD22L,1.0,-25
1048561,20/01/2023,012,-,2000801,OL9267SS22L,1.0,-25
1048562,20/01/2023,012,-,2000801,OL9273BB21L,1.0,-25
1048563,20/01/2023,012,-,2000801,OL9273SS21L,1.0,-25
1048564,20/01/2023,012,-,2000801,OL9346SR22L,1.0,-25