In [8]:
import pandas as pd
import numpy as np
import matplotlib as mp

filename = "Data/Sell_In.csv"
df_SI = pd.read_csv(filename)

/var/folders/qm/bcpltlfs7qj3bt894_htm00c0000gn/T/ipykernel_2257/4245869906.py:6: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_SI = pd.read_csv(filename)

In [9]:
df_SI

,Data,Cod. Vendedor Base,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
0,05/01/2023,33,-,110009,OJNYR08S-7,3,30.0
1,05/01/2023,31,-,30031,OJCHB01SG,3,20.0
2,05/01/2023,31,-,30031,OJNYR23Y-8,3,20.0
3,05/01/2023,31,400024,40002412,OJUR01-7,3,20.0
4,05/01/2023,31,400024,40002409,OJBMS01,3,20.0
...,...,...,...,...,...,...,...
415146,31/12/2024,-,-,-,Sets,2,20.0
415147,31/12/2024,-,-,-,Smartwatches Men,2,20.0
415148,31/12/2024,-,-,-,Smartwatches Women,2,20.0
415149,31/12/2024,-,-,-,Watches Men,2,20.0
415150,31/12/2024,-,-,-,Watches Women,2,20.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415151 entries, 0 to 415150
Data columns (total 7 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Data                  415151 non-null  object
 1   Cod. Vendedor Base    415151 non-null  object
 2   Cod. Cliente Holding  415151 non-null  object
 3   Cod. Cliente          415151 non-null  object
 4   Cod. Artigo           415151 non-null  object
 5   Quantidade            415151 non-null  int64
 6   Valor Líq. EUR        415151 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 22.2+ MB

In [11]:
df_SI.shape

(415151, 7)

In [12]:
df_SI.head(5)

,Data,Cod. Vendedor Base,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
0,05/01/2023,33,-,110009,OJNYR08S-7,3,30.0
1,05/01/2023,31,-,30031,OJCHB01SG,3,20.0
2,05/01/2023,31,-,30031,OJNYR23Y-8,3,20.0
3,05/01/2023,31,400024,40002412,OJUR01-7,3,20.0
4,05/01/2023,31,400024,40002409,OJBMS01,3,20.0

In [13]:
df_SI.tail(5)

,Data,Cod. Vendedor Base,Cod. Cliente Holding,Cod. Cliente,Cod. Artigo,Quantidade,Valor Líq. EUR
415146,31/12/2024,-,-,-,Sets,2,20.0
415147,31/12/2024,-,-,-,Smartwatches Men,2,20.0
415148,31/12/2024,-,-,-,Smartwatches Women,2,20.0
415149,31/12/2024,-,-,-,Watches Men,2,20.0
415150,31/12/2024,-,-,-,Watches Women,2,20.0